import { useEffect } from 'react';
import Head from 'next/head';
import styles from '../styles/Home.module.css';

const Home = () => {
  useEffect(() => {
    window.location.href = 'https://read.cv/dickymr';
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Under Construction</h1>
      </main>
    </div>
  );
};

export default Home;
